### ISSUE TITLE
ModuleNotFoundError: No module named 'jax.numpy'; 'jax' is not a package

### ISSUE THREAD

**Issue by bayun2016** [AIFSH/ComfyUI-ChatTTS#13]
File "E:\dev_tools\ComfyUI-aki-v1.3\python\lib\site-packages\einx\backend\_jax.py", line 11, in create
    import jax.numpy as jnp
ModuleNotFoundError: No module named 'jax.numpy'; 'jax' is not a package
我尝试windows下安装jax，安装成功后后台有警告：WARNING: jax 0.4.21 does not provide the extra 'cuda12'
重启comfyui后仍然报这个错误
cuda版本是12.1，是否由于jax不支持cuda12导致无法加载节点😔

**Comment by wfjsw** [comment]
please paste the entire stack trace

**Comment by bayun2016** [comment]
> please paste the entire stack trace

!!!ChatTTS path was added to E:\dev_tools\ComfyUI-aki-v1.3\python\lib\site-packages/ChatTTS.pth
 if meet `No module` error,try `python main.py` again
ChatTTS use cache models,make sure your 'pretrained_models' complete
Traceback (most recent call last):
  File "E:\dev_tools\ComfyUI-aki-v1.3\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-ChatTTS\__init__.py", line 36, in <module>
    from .nodes import PreViewAudio,ChatTTS
  File "E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-ChatTTS\nodes.py", line 6, in <module>
    from ChatTTS import Chat
  File "E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-ChatTTS\ChatTTS\__init__.py", line 1, in <module>
    from .core import Chat
  File "E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-ChatTTS\ChatTTS\core.py", line 9, in <module>
    from .model.dvae import DVAE
  File "E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-ChatTTS\ChatTTS\model\dvae.py", line 3, in <module>
    from vector_quantize_pytorch import GroupedResidualFSQ
  File "E:\dev_tools\ComfyUI-aki-v1.3\python\lib\site-packages\vector_quantize_pytorch\__init__.py", line 1, in <module>
    from vector_quantize_pytorch.vector_quantize_pytorch import VectorQuantize
  File "E:\dev_tools\ComfyUI-aki-v1.3\python\lib\site-packages\vector_quantize_pytorch\vector_quantize_pytorch.py", line 12, in <module>
    import einx
  File "E:\dev_tools\ComfyUI-aki-v1.3\python\lib\site-packages\einx\__init__.py", line 5, in <module>
    from . import backend
  File "E:\dev_tools\ComfyUI-aki-v1.3\python\lib\site-packages\einx\backend\__init__.py", line 1, in <module>
    from .register import register_for_module, register, get, backends, numpy
  File "E:\dev_tools\ComfyUI-aki-v1.3\python\lib\site-packages\einx\backend\register.py", line 53, in <module>
    register_for_module("jax", _jax.create)
  File "E:\dev_tools\ComfyUI-aki-v1.3\python\lib\site-packages\einx\backend\register.py", line 19, in register_for_module
    register(backend_factory())
  File "E:\dev_tools\ComfyUI-aki-v1.3\python\lib\site-packages\einx\backend\_jax.py", line 11, in create
    import jax.numpy as jnp
ModuleNotFoundError: No module named 'jax.numpy'; 'jax' is not a package

Cannot import E:\dev_tools\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-ChatTTS module for custom nodes: No module named 'jax.numpy'; 'jax' is not a package

**Comment by wfjsw** [comment]
> The problem should also be fixed with the latest source version of einx (see [this commit](https://github.com/fferflo/einx/commit/affbd5c94064e344f52fb0fdb5e34d3b8e7bc686)), so you could try updating einx:
> 
> ```
> python -m pip install --upgrade git+https://github.com/fferflo/einx.git
> ```

_Originally posted by @fferflo in https://github.com/heshengtao/comfyui_LLM_party/issues/35#issuecomment-2248364434_

**Comment by bayun2016** [comment]
> > The problem should also be fixed with the latest source version of einx (see [this commit](https://github.com/fferflo/einx/commit/affbd5c94064e344f52fb0fdb5e34d3b8e7bc686)), so you could try updating einx:
> > ```
> > python -m pip install --upgrade git+https://github.com/fferflo/einx.git
> > ```
> 
> _Originally posted by @fferflo in [heshengtao/comfyui_LLM_party#35 (comment)](https://github.com/heshengtao/comfyui_LLM_party/issues/35#issuecomment-2248364434)_

Thanks very much. I'll try to update einx.

**Comment by bayun2016** [comment]
执行python -m pip install --upgrade git+https://github.com/fferflo/einx.git，看命令行，都是已经满足依赖版本的提示，没有新装的依赖：
E:\dev_tools\ComfyUI-aki-v1.3\python>python -m pip install --upgrade git+https://github.com/fferflo/einx.git
Collecting git+https://github.com/fferflo/einx.git
  Cloning https://github.com/fferflo/einx.git to c:\users\administrator\appdata\local\temp\pip-req-build-iyz0esrt
  Running command git clone --filter=blob:none --quiet https://github.com/fferflo/einx.git 'C:\Users\Administrator\AppData\Local\Temp\pip-req-build-iyz0esrt'
  Resolved https://github.com/fferflo/einx.git to commit b809bc78102f1e3f959df3768068fe0fb036cc86
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in e:\dev_tools\comfyui-aki-v1.3\python\lib\site-packages (from einx==0.3.0) (1.26.4)
Requirement already satisfied: sympy in e:\dev_tools\comfyui-aki-v1.3\python\lib\site-packages (from einx==0.3.0) (1.13.0)
Requirement already satisfied: frozendict in e:\dev_tools\comfyui-aki-v1.3\python\lib\site-packages (from einx==0.3.0) (2.4.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in e:\dev_tools\comfyui-aki-v1.3\python\lib\site-packages (from sympy->einx==0.3.0) (1.3.0)

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

E:\dev_tools\ComfyUI-aki-v1.3\python>

然后重启秋叶启动器，还是没能正确导入节点，错误仍然同上

**Comment by wfjsw** [comment]
Can you paste a new stack trace

**Comment by bayun2016** [comment]
> Can you paste a new stack trace

不好意思，我没说清楚，有两个错误，我把截图发下；
第一个：
![image](https://github.com/user-attachments/assets/0e816581-4523-4e91-99a7-b624ba3ad399)
第二个：
![image](https://github.com/user-attachments/assets/050696b8-9eef-4280-99fb-27526fd95aa9)

**Comment by wfjsw** [comment]
Seems you are still on a old version. This might be caused by some other extension locking the version of einx, or something is broken in your packages. Try to remove multiple times and install einx to see if issue persists.

**Comment by bayun2016** [comment]
> Seems you are still on a old version. This might be caused by some other extension locking the version of einx, or something is broken in your packages. Try to remove multiple times and install einx to see if issue persists.

十分感谢，刚卸载了einx后重装，已经能够正常运行节点了：
![image](https://github.com/user-attachments/assets/0a22fea9-c0a9-4985-b139-32a3d88ccd8d)
